// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gukbteeyusfddcctogxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1a2J0ZWV5dXNmZGRjY3RvZ3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODY4ODIsImV4cCI6MjA3MjE2Mjg4Mn0.DQ2kWaOYEsVxR8OcZ5FdP8PvyxVjyBWpETBp9B8h9Go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});